language: python

python:
    - "3.6"
    - "3.7-dev"

env:
    global:
        - DJANGO_SETTINGS_MODULE="travis_ci.settings"

before_install:
    - cd backend

branches:
    only:
        - master

install:
    - pip install -r requirements.txt

script:
    - python manage.py test
